const CONFIG={WEDDING_DATE:"2026-11-14T17:00:00+06:00",WHATSAPP_NUMBER:"996555123456"};
const $=(s,scope=document)=>scope.querySelector(s);const $$=(s,scope=document)=>[...scope.querySelectorAll(s)];
const audio=$("#bgMusic"),music=$("#musicToggle"),openLink=$("#openInvitation");
function setMusic(on){music?.classList.toggle("playing",on);music?.setAttribute("aria-label",on?"Музыканы токтотуу":"Музыканы күйгүзүү")}
async function startMusic(){if(!audio)return;try{audio.volume=.72;await audio.play();setMusic(true)}catch(e){setMusic(false)}}
openLink?.addEventListener("click",()=>{startMusic();setTimeout(initReveal,80)});
music?.addEventListener("click",async()=>{if(!audio)return;if(audio.paused)await startMusic();else{audio.pause();setMusic(false)}});
function initReveal(){const items=$$(".reveal:not(.visible)");if(!("IntersectionObserver" in window)){items.forEach(x=>x.classList.add("visible"));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.08});items.forEach(x=>io.observe(x))}
function initCountdown(){const target=new Date(CONFIG.WEDDING_DATE).getTime(),pad=n=>String(n).padStart(2,"0"),nodes={d:$("#days"),h:$("#hours"),m:$("#minutes"),s:$("#seconds")};function tick(){let x=Math.max(0,target-Date.now());nodes.d.textContent=pad(Math.floor(x/86400000));nodes.h.textContent=pad(Math.floor((x%86400000)/3600000));nodes.m.textContent=pad(Math.floor((x%3600000)/60000));nodes.s.textContent=pad(Math.floor((x%60000)/1000))}tick();setInterval(tick,1000)}
function initRSVP(){const form=$("#rsvpForm");form?.addEventListener("submit",e=>{e.preventDefault();const name=$("#guestName").value.trim(),att=$("#attendance").value,count=$("#guestCount").value,note=$("#guestMessage").value.trim();if(!name)return $("#guestName").focus();const lines=[`Саламатсызбы! Мен ${name}.`,att==="Ооба, катышам"?`Тойго катышам. Биз ${count} адам болобуз.`:"Тилекке каршы, тойго катыша албайм.",note?`Билдирүү: ${note}`:""].filter(Boolean);window.open(`https://wa.me/${CONFIG.WHATSAPP_NUMBER}?text=${encodeURIComponent(lines.join("\n"))}`,"_blank","noopener,noreferrer")})}
document.addEventListener("DOMContentLoaded",()=>{initCountdown();initRSVP();initReveal()});